version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: jenkins-docker.Dockerfile
    container_name: jenkins
    user: root                            # Run as root for Docker socket access
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - java-maven-app_jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.kube/config:/root/.kube/config:ro   # Mount kubeconfig for Kubernetes access
      - ${HOME}/.minikube:/root/.minikube
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - KUBECONFIG=/root/.kube/config

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql/data

  trivy:
    image: aquasec/trivy:latest
    container_name: trivy
    entrypoint: ["sleep", "infinity"]
    volumes:
      - trivy-cache:/root/.cache/trivy

volumes:
  java-maven-app_jenkins_home:
  postgresql:
  trivy-cache:
