apiVersion: v1
kind: Service
metadata:
  name: java-maven-app-service
spec:
  selector:
    app: java-maven-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: NodePort  # You can switch to LoadBalancer if on a cloud provider
